GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTMwMTgxNTAsImV4cCI6MTY5MzAxODQ1MCwiYXVkIjoiNjRlN2FiNzQ1MzJjYTNiOTJlNjA5NzY2IiwiaXNzIjoiZ3JhZHN0ZW0uY29tIn0.oTgarqyuqv4Epjt1FL8kMHMglMErOX4Dua8xa889dFc

###
POST https://jobs.learnerabdul.com/api/v1/ HTTP/1.1

{
  "companyname":"gradstem" ,
  "jobtitle":"software dev",
  "jobid": "1234"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"rizwanew@gmail.com",
    "password":"12345"
}

###
POST http://localhost:3000/api/v0/companies
Content-Type: application/json

{
    "companyName":"gradstem",
    "h1b":0
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json


{
    "email":"mustafa@gmail.com",
    "password":"1234"
}

###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTI4NTA0ODUsImV4cCI6MTcyNDQwODA4NSwiYXVkIjoiNjRlNmQ5MzU3MTM5ZTdmMTBmOWJlZTVhIiwiaXNzIjoiZ3JhZHN0ZW0uY29tIn0.nFHaMw6sjxCLzUespfgRSyYah3vhm51K5s9UNcjlNUY"
}

###
DELETE http://localhost:3000/auth/logout