GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTMyMzg3MjEsImV4cCI6MTY5MzIzOTAyMSwiYXVkIjoiNjRlN2FiNzQ1MzJjYTNiOTJlNjA5NzY2IiwiaXNzIjoiZ3JhZHN0ZW0uY29tIn0.5UdbJSKskxwTimhuBRTZED98fa0wIr0IoZ4-vesIpzE

###
POST https://jobs.learnerabdul.com/api/v1/ HTTP/1.1

{
  "companyname":"gradstem" ,
  "jobtitle":"software dev",
  "jobDescription":"this is a software development job",
  "jobid": "1234"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"rizwanew@gmail.com",
    "password":"12345"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"rizwanew@gmail.com",
    "password":"12345"
}

###
POST http://localhost:3000/api/v0/companies
Content-Type: application/json

{
    "companyName":"stemgrad",
    "h1b":1
}

###
POST http://localhost:3000/api/v0/jobs HTTP/1.1
Content-Type: application/json


{
  "companyname":"gradstem" ,
  "company":"64eabd81dd9be18e5906eb28",
  "jobTitle":"Test engineer",
  "jobDescription":"this is a AI Engineer job",
  "jobid": "1234",
  "openaiEmbeddings":"some job",
    "domain":"test engineer "
}


###
GET http://localhost:3000/api/v0/similarity
Content-Type: application/json

{
    "text":"java job"
}

###
GET http://localhost:3000/api/v0/jobs HTTP/1.1
Content-Type: application/json


###
DELETE  http://localhost:3000/api/v0/jobs/ HTTP/1.1
Content-Type: application/json

{
    "id":"64ee1ade8a753b52332564e4"
}



###
POST http://localhost:3000/auth/login
Content-Type: application/json


{
    "email":"mustafa@gmail.com",
    "password":"1234"
}

###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTI4NTA0ODUsImV4cCI6MTcyNDQwODA4NSwiYXVkIjoiNjRlNmQ5MzU3MTM5ZTdmMTBmOWJlZTVhIiwiaXNzIjoiZ3JhZHN0ZW0uY29tIn0.nFHaMw6sjxCLzUespfgRSyYah3vhm51K5s9UNcjlNUY"
}

###
DELETE http://localhost:3000/auth/logout