GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTM3ODM3MTYsImV4cCI6MTY5NjM3NTcxNiwiYXVkIjoiNjRlYTkwZTYwNzZjZmYxM2M2ZmM1YzdjIiwiaXNzIjoiZ3JhZHN0ZW0uY29tIn0.FHdEZ90rmVZDl2KeKqS17k4PwWZIV5CwGBqPDXnQF1A
###
GET http://localhost:3000/api/v0/similarity
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTM3ODM3MTYsImV4cCI6MTY5NjM3NTcxNiwiYXVkIjoiNjRlYTkwZTYwNzZjZmYxM2M2ZmM1YzdjIiwiaXNzIjoiZ3JhZHN0ZW0uY29tIn0.FHdEZ90rmVZDl2KeKqS17k4PwWZIV5CwGBqPDXnQF1A
Content-Type: application/json

{
    "text":" development"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"rizwanew@gmail.com",
    "password":"12345"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"rizwanew@gmail.com",
    "password":"12345"
}

###
POST http://localhost:3000/api/v0/companies
Content-Type: application/json

{
    "companyName":"stemgrad",
    "h1b":1
}

###
POST http://localhost:3000/api/v0/jobs HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTM3ODM3MTYsImV4cCI6MTY5NjM3NTcxNiwiYXVkIjoiNjRlYTkwZTYwNzZjZmYxM2M2ZmM1YzdjIiwiaXNzIjoiZ3JhZHN0ZW0uY29tIn0.FHdEZ90rmVZDl2KeKqS17k4PwWZIV5CwGBqPDXnQF1A
Content-Type: application/json

{
  "company":"64eabd81dd9be18e5906eb28",
  "jobTitle":"xyz",
  "jobDescription":"this is a software Engineer job",
  "jobid": "1234",
  "applyLink":"jobs.google.com",
  "domain":"xyz "
}


###
GET http://localhost:3000/api/v0/similarity
Content-Type: application/json

{
    "text":"software development"
}

###
GET http://localhost:3000/api/v0/jobs/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTM3ODM3MTYsImV4cCI6MTY5NjM3NTcxNiwiYXVkIjoiNjRlYTkwZTYwNzZjZmYxM2M2ZmM1YzdjIiwiaXNzIjoiZ3JhZHN0ZW0uY29tIn0.FHdEZ90rmVZDl2KeKqS17k4PwWZIV5CwGBqPDXnQF1A
Content-Type: application/json


###
DELETE  http://localhost:3000/api/v0/jobs/64ee1b2a8a753b52332564e8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTM3ODM3MTYsImV4cCI6MTY5NjM3NTcxNiwiYXVkIjoiNjRlYTkwZTYwNzZjZmYxM2M2ZmM1YzdjIiwiaXNzIjoiZ3JhZHN0ZW0uY29tIn0.FHdEZ90rmVZDl2KeKqS17k4PwWZIV5CwGBqPDXnQF1A
Content-Type: application/json



###
PATCH  http://localhost:3000/api/v0/jobs/64ee1b2a8a753b52332564e8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTM3ODM3MTYsImV4cCI6MTY5NjM3NTcxNiwiYXVkIjoiNjRlYTkwZTYwNzZjZmYxM2M2ZmM1YzdjIiwiaXNzIjoiZ3JhZHN0ZW0uY29tIn0.FHdEZ90rmVZDl2KeKqS17k4PwWZIV5CwGBqPDXnQF1A
Content-Type: application/json

{
  "company":"64eabd81dd9be18e5906eb28",
  "jobTitle":" new full stack engineer",
  "jobDescription":"this is a software Engineer job",
  "jobid": "1234",
  "openaiEmbeddings":"some job",
  "domain":" engineer "
}


###
POST http://localhost:3000/auth/login
Content-Type: application/json


{
    "email":"mustafa@gmail.com",
    "password":"1234"
}

###
POST http://localhost:3000/auth/refresh_token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTI4NTA0ODUsImV4cCI6MTcyNDQwODA4NSwiYXVkIjoiNjRlNmQ5MzU3MTM5ZTdmMTBmOWJlZTVhIiwiaXNzIjoiZ3JhZHN0ZW0uY29tIn0.nFHaMw6sjxCLzUespfgRSyYah3vhm51K5s9UNcjlNUY"
}

###
DELETE http://localhost:3000/auth/logout